/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type The360GivingDataStandardSchema = {
  id?: Identifier;
  title?: Title;
  description?: Description;
  currency?: Currency;
  amountAppliedFor?: AmountAppliedFor;
  amountAwarded?: AmountAwarded;
  amountDisbursed?: AmountDisbursed;
  awardDate?: AwardDate;
  url?: URL;
  plannedDates?: PlannedDates;
  actualDates?: ActualDates;
  recipientIndividual?: RecipientInd;
  toIndividualsDetails?: ToIndividualsDetails;
  recipientOrganization?: RecipientOrg;
  beneficiaryLocation?: BeneficiaryLocation;
  fundingOrganization?: FundingOrg;
  grantProgramme?: GrantProgramme;
  fromOpenCall?: FromAnOpenCall;
  fundingType?: FundingType;
  classifications?: Classifications;
  relatedDocument?: RelatedDocument;
  /**
   * -
   */
  applicationTransaction?: Transaction[];
  /**
   * -
   */
  commitmentTransaction?: Transaction[];
  /**
   * -
   */
  disbursementTransaction?: Transaction[];
  relatedActivity?: RelatedActivity;
  dateModified?: LastModified7;
  dataSource?: DataSource;
  regrantType?: ForRegrantType;
  locationScope?: LocationScope;
  [k: string]: unknown;
} & {
  [k: string]: unknown;
};
/**
 * The unique identifier for this grant. Made up of your 360Giving prefix, and an identifier from your records. See the [360Giving Grant identifier guidance](https://standard.threesixtygiving.org/en/latest/technical/identifiers/#grant-identifier) for details.
 */
export type Identifier = string;
/**
 * A title for this grant activity. This should be under 140 characters long.
 */
export type Title = string;
/**
 * A short description of this grant activity.
 */
export type Description = string;
/**
 * The currency used in amounts. Use the three-letter currency code from [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) eg: Use GBP for Pounds Sterling.
 */
export type Currency =
  | "ADP"
  | "AED"
  | "AFA"
  | "AFN"
  | "ALK"
  | "ALL"
  | "AMD"
  | "ANG"
  | "AOA"
  | "AOK"
  | "AON"
  | "AOR"
  | "ARA"
  | "ARP"
  | "ARS"
  | "ARY"
  | "ATS"
  | "AUD"
  | "AWG"
  | "AYM"
  | "AZM"
  | "AZN"
  | "BAD"
  | "BAM"
  | "BBD"
  | "BDT"
  | "BEC"
  | "BEF"
  | "BEL"
  | "BGJ"
  | "BGK"
  | "BGL"
  | "BGN"
  | "BHD"
  | "BIF"
  | "BMD"
  | "BND"
  | "BOB"
  | "BOP"
  | "BOV"
  | "BRB"
  | "BRC"
  | "BRE"
  | "BRL"
  | "BRN"
  | "BRR"
  | "BSD"
  | "BTN"
  | "BUK"
  | "BWP"
  | "BYB"
  | "BYN"
  | "BYR"
  | "BZD"
  | "CAD"
  | "CDF"
  | "CHC"
  | "CHE"
  | "CHF"
  | "CHW"
  | "CLF"
  | "CLP"
  | "CNY"
  | "COP"
  | "COU"
  | "CRC"
  | "CSD"
  | "CSJ"
  | "CSK"
  | "CUC"
  | "CUP"
  | "CVE"
  | "CYP"
  | "CZK"
  | "DDM"
  | "DEM"
  | "DJF"
  | "DKK"
  | "DOP"
  | "DZD"
  | "ECS"
  | "ECV"
  | "EEK"
  | "EGP"
  | "ERN"
  | "ESA"
  | "ESB"
  | "ESP"
  | "ETB"
  | "EUR"
  | "FIM"
  | "FJD"
  | "FKP"
  | "FRF"
  | "GBP"
  | "GEK"
  | "GEL"
  | "GHC"
  | "GHP"
  | "GHS"
  | "GIP"
  | "GMD"
  | "GNE"
  | "GNF"
  | "GNS"
  | "GQE"
  | "GRD"
  | "GTQ"
  | "GWE"
  | "GWP"
  | "GYD"
  | "HKD"
  | "HNL"
  | "HRD"
  | "HRK"
  | "HTG"
  | "HUF"
  | "IDR"
  | "IEP"
  | "ILP"
  | "ILR"
  | "ILS"
  | "INR"
  | "IQD"
  | "IRR"
  | "ISJ"
  | "ISK"
  | "ITL"
  | "JMD"
  | "JOD"
  | "JPY"
  | "KES"
  | "KGS"
  | "KHR"
  | "KMF"
  | "KPW"
  | "KRW"
  | "KWD"
  | "KYD"
  | "KZT"
  | "LAJ"
  | "LAK"
  | "LBP"
  | "LKR"
  | "LRD"
  | "LSL"
  | "LSM"
  | "LTL"
  | "LTT"
  | "LUC"
  | "LUF"
  | "LUL"
  | "LVL"
  | "LVR"
  | "LYD"
  | "MAD"
  | "MDL"
  | "MGA"
  | "MGF"
  | "MKD"
  | "MLF"
  | "MMK"
  | "MNT"
  | "MOP"
  | "MRO"
  | "MRU"
  | "MTL"
  | "MTP"
  | "MUR"
  | "MVQ"
  | "MVR"
  | "MWK"
  | "MXN"
  | "MXP"
  | "MXV"
  | "MYR"
  | "MZE"
  | "MZM"
  | "MZN"
  | "NAD"
  | "NGN"
  | "NIC"
  | "NIO"
  | "NLG"
  | "NOK"
  | "NPR"
  | "NZD"
  | "OMR"
  | "PAB"
  | "PEH"
  | "PEI"
  | "PEN"
  | "PES"
  | "PGK"
  | "PHP"
  | "PKR"
  | "PLN"
  | "PLZ"
  | "PTE"
  | "PYG"
  | "QAR"
  | "RHD"
  | "ROK"
  | "ROL"
  | "RON"
  | "RSD"
  | "RUB"
  | "RUR"
  | "RWF"
  | "SAR"
  | "SBD"
  | "SCR"
  | "SDD"
  | "SDG"
  | "SDP"
  | "SEK"
  | "SGD"
  | "SHP"
  | "SIT"
  | "SKK"
  | "SLL"
  | "SOS"
  | "SRD"
  | "SRG"
  | "SSP"
  | "STD"
  | "STN"
  | "SUR"
  | "SVC"
  | "SYP"
  | "SZL"
  | "THB"
  | "TJR"
  | "TJS"
  | "TMM"
  | "TMT"
  | "TND"
  | "TOP"
  | "TPE"
  | "TRL"
  | "TRY"
  | "TTD"
  | "TWD"
  | "TZS"
  | "UAH"
  | "UAK"
  | "UGS"
  | "UGW"
  | "UGX"
  | "USD"
  | "USN"
  | "USS"
  | "UYI"
  | "UYN"
  | "UYP"
  | "UYU"
  | "UZS"
  | "VEB"
  | "VEF"
  | "VES"
  | "VNC"
  | "VND"
  | "VUV"
  | "WST"
  | "XAF"
  | "XAG"
  | "XAU"
  | "XBA"
  | "XBB"
  | "XBC"
  | "XBD"
  | "XCD"
  | "XDR"
  | "XEU"
  | "XFO"
  | "XFU"
  | "XOF"
  | "XPD"
  | "XPF"
  | "XPT"
  | "XRE"
  | "XSU"
  | "XTS"
  | "XUA"
  | "XXX"
  | "YDD"
  | "YER"
  | "YUD"
  | "YUM"
  | "YUN"
  | "ZAL"
  | "ZAR"
  | "ZMK"
  | "ZMW"
  | "ZRN"
  | "ZRZ"
  | "ZWC"
  | "ZWD"
  | "ZWL"
  | "ZWN"
  | "ZWR";
/**
 * Total amount applied for in numbers (do not include commas or currency symbols such as £). If you have provided detailed transaction information on a separate table, this should equal the sum of all the application transactions for this grant.
 */
export type AmountAppliedFor = number;
/**
 * Total amount awarded in numbers (do not include commas or currency symbols such as £). If you have provided detailed transaction information on a separate table, this should equal the sum of all the award transactions for this grant.
 */
export type AmountAwarded = number;
/**
 * Total amount disbursed (paid) to this grantee when this record was last updated (in numbers: do not include commas or currency symbols such as £)). If you have provided detailed transaction information on a separate table, this should equal the sum of all the disbursement transactions for this grant.
 */
export type AmountDisbursed = number;
/**
 * When the decision to award this grant was made. The date must be written as YYYY-MM-DD, or in full date-time format.
 */
export type AwardDate = {
  [k: string]: unknown;
} & string;
/**
 * A URL (Web Address) where further information about this grant can be found. This could point to the website of the recipient organisation, or might link to further details on the funders website.
 */
export type URL = string;
/**
 * The title of this event
 */
export type Title1 = string;
/**
 * All events should have a start date. Dates must be in YYYY-MM-DD or date-time format. If the month or day are not available, these may be omitted.
 */
export type StartDate = {
  [k: string]: unknown;
} & string;
/**
 * An end date for the grant. Dates must be in YYYY-MM-DD or date-time format. If the month or day are not available, these may be omitted.
 */
export type EndDate = {
  [k: string]: unknown;
} & string;
/**
 * The duration of the grant, in months. Must be in number format.
 */
export type DurationMonths = number;
/**
 * A description of this event
 */
export type Description1 = string;
/**
 * When was information about this event last modified? A full date-time should be given. Usually this can be generated automatically by the software managing or exporting this data.
 */
export type LastModified = string;
/**
 * When the recipient organisation intends this activity to take place. A date range can include a start date and duration in months, or a start and end date.
 */
export type PlannedDates = Event[];
/**
 * When did this grant activity actually take place. Dates must be in YYYY-MM-DD or date-time format. A date range can include a start date and duration in months, or a start and end date.
 */
export type ActualDates = Event[];
/**
 * A unique identifier which identifies the person in the dataset
 */
export type Identifier1 = string;
/**
 * The Person's full name or a generic name such as "Individual Recipient"
 */
export type Name = string;
/**
 * A code referring to the reason(s) for a grant to an individual. The value for this field should be drawn from the Grant to Individuals Reason codelist
 */
export type PrimaryGrantReason = string;
/**
 * A code referring to the reason(s) for a grant to an individual. The value for this field should be drawn from the Grant to Individuals Reason codelist
 */
export type SecondaryGrantReason = string;
/**
 * A code referring to the purpose(s) for a grant to an individual. The value(s) for this field should be drawn from the Grant to Individuals Purpose codelist
 */
export type GrantPurpose = string[];
/**
 * Details of the recipient of this grant.
 *
 * @minItems 1
 */
export type RecipientOrg = [Organization, ...Organization[]];
/**
 * A globally unique identifier for this organisation. This is important to enable data on funders and recipients to be linked up across different grant-makers. The [Organisation Identifier Standard](https://standard.threesixtygiving.org/en/latest/technical/identifiers/#organisation-identifier) guidance explains how to create this ID, based either on the known company or charity number, or upon identifiers held in the grantmaker's internal systems.
 */
export type Identifier2 = string;
/**
 * Organisation name
 */
export type Name1 = string;
/**
 * The department or sub-unit of this organisation making or receiving the grant.
 */
export type Department = string;
/**
 * The contact person at this organisation.
 */
export type ContactName = string;
/**
 * Registered charity number, if applicable.
 */
export type CharityNumber = string;
/**
 * Registered UK company number, if applicable.
 */
export type CompanyNumber = string;
/**
 * Organisation address building number and street name.
 */
export type StreetAddress = string;
/**
 * Organisation address city or town.
 */
export type City = string;
/**
 * Organisation address county
 */
export type County = string;
/**
 * Organisation address country
 */
export type Country = string;
/**
 * Organisation address postal code.
 */
export type PostalCode = string;
/**
 * Contact phone number.
 */
export type PhoneNumber = string;
/**
 * An alternative name for this organisation (e.g. trading name)
 */
export type AlternateName = string;
/**
 * The email address for this organisation.
 */
export type Email = string;
/**
 * A short description of this organisation and its area of work
 */
export type Description2 = string;
/**
 * A description of this organisation
 */
export type OrganisationType = string | null;
/**
 * A web address for the Organisation
 */
export type WebAddress = string;
/**
 * Location identifier
 */
export type Identifier3 = string;
/**
 * A name for this location.
 */
export type Name2 = string | null;
/**
 * The 2-character ISO Country Code of the location of this activity. Taken from [ISO-3166-1-alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
 */
export type CountryCode =
  | (
      | "AF"
      | "AX"
      | "AL"
      | "DZ"
      | "AS"
      | "AD"
      | "AO"
      | "AI"
      | "AQ"
      | "AG"
      | "AR"
      | "AM"
      | "AW"
      | "AU"
      | "AT"
      | "AZ"
      | "BS"
      | "BH"
      | "BD"
      | "BB"
      | "BY"
      | "BE"
      | "BZ"
      | "BJ"
      | "BM"
      | "BT"
      | "BO"
      | "BQ"
      | "BA"
      | "BW"
      | "BV"
      | "BR"
      | "IO"
      | "BN"
      | "BG"
      | "BF"
      | "BI"
      | "KH"
      | "CM"
      | "CA"
      | "CV"
      | "KY"
      | "CF"
      | "TD"
      | "CL"
      | "CN"
      | "CX"
      | "CC"
      | "CO"
      | "KM"
      | "CG"
      | "CD"
      | "CK"
      | "CR"
      | "CI"
      | "HR"
      | "CU"
      | "CW"
      | "CY"
      | "CZ"
      | "DK"
      | "DJ"
      | "DM"
      | "DO"
      | "EC"
      | "EG"
      | "SV"
      | "GQ"
      | "ER"
      | "EE"
      | "ET"
      | "FK"
      | "FO"
      | "FJ"
      | "FI"
      | "FR"
      | "GF"
      | "PF"
      | "TF"
      | "GA"
      | "GM"
      | "GE"
      | "DE"
      | "GH"
      | "GI"
      | "GR"
      | "GL"
      | "GD"
      | "GP"
      | "GU"
      | "GT"
      | "GG"
      | "GN"
      | "GW"
      | "GY"
      | "HT"
      | "HM"
      | "VA"
      | "HN"
      | "HK"
      | "HU"
      | "IS"
      | "IN"
      | "ID"
      | "IR"
      | "IQ"
      | "IE"
      | "IM"
      | "IL"
      | "IT"
      | "JM"
      | "JP"
      | "JE"
      | "JO"
      | "KZ"
      | "KE"
      | "KI"
      | "KP"
      | "KR"
      | "KW"
      | "KG"
      | "LA"
      | "LV"
      | "LB"
      | "LS"
      | "LR"
      | "LY"
      | "LI"
      | "LT"
      | "LU"
      | "MO"
      | "MK"
      | "MG"
      | "MW"
      | "MY"
      | "MV"
      | "ML"
      | "MT"
      | "MH"
      | "MQ"
      | "MR"
      | "MU"
      | "YT"
      | "MX"
      | "FM"
      | "MD"
      | "MC"
      | "MN"
      | "ME"
      | "MS"
      | "MA"
      | "MZ"
      | "MM"
      | "NA"
      | "NR"
      | "NP"
      | "NL"
      | "NC"
      | "NZ"
      | "NI"
      | "NE"
      | "NG"
      | "NU"
      | "NF"
      | "MP"
      | "NO"
      | "OM"
      | "PK"
      | "PW"
      | "PS"
      | "PA"
      | "PG"
      | "PY"
      | "PE"
      | "PH"
      | "PN"
      | "PL"
      | "PT"
      | "PR"
      | "QA"
      | "RE"
      | "RO"
      | "RU"
      | "RW"
      | "BL"
      | "SH"
      | "KN"
      | "LC"
      | "MF"
      | "PM"
      | "VC"
      | "WS"
      | "SM"
      | "ST"
      | "SA"
      | "SN"
      | "RS"
      | "SC"
      | "SL"
      | "SG"
      | "SX"
      | "SK"
      | "SI"
      | "SB"
      | "SO"
      | "ZA"
      | "GS"
      | "SS"
      | "ES"
      | "LK"
      | "SD"
      | "SR"
      | "SJ"
      | "SZ"
      | "SE"
      | "CH"
      | "SY"
      | "TW"
      | "TJ"
      | "TZ"
      | "TH"
      | "TL"
      | "TG"
      | "TK"
      | "TO"
      | "TT"
      | "TN"
      | "TR"
      | "TM"
      | "TC"
      | "TV"
      | "UG"
      | "UA"
      | "AE"
      | "GB"
      | "US"
      | "UM"
      | "UY"
      | "UZ"
      | "VU"
      | "VE"
      | "VN"
      | "VG"
      | "VI"
      | "WF"
      | "EH"
      | "YE"
      | "ZM"
      | "ZW"
    )
  | null;
/**
 * The latitude of a point location. Using [WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System) standard, for example 51.501502
 */
export type Latitude = number | null;
/**
 * The longitude of a point location. Using [WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System) standard, for example -0.175269
 */
export type Longitude = number | null;
/**
 * A description of this location. This could include details of the element of the activity that takes place here.
 */
export type Description3 = string | null;
/**
 * A code referring to a geographical area, drawn from an established gazetteer such as the [ONS Register of Geographic Codes](https://en.wikipedia.org/wiki/ONS_coding_system) in the UK. For example, the code for a local authority ward, or parliamentary constituency.
 */
export type GeographicCode = string | null;
/**
 * The type of Geographic Code (geoCode) used (e.g. Ward, Parliamentary Constituency etc.). This value for this field should be drawn from the [codelist of geographic code types](https://github.com/ThreeSixtyGiving/standard/tree/master/codelists/geoCodeType.csv).
 */
export type GeographicCodeType = string | null;
/**
 * When was this location information last modified? A full date-time should be given. Usually this can be generated automatically by the software managing or exporting this data.
 */
export type LastModified1 = string;
/**
 * Information about the location of the organisation.
 */
export type Location = Location1[];
/**
 * When was the organisation information for this grant last modified? A full date-time should be given. Usually this can be generated automatically by the software managing or exporting this data.
 */
export type LastModified2 = string;
/**
 * Information about the location of beneficiaries. Further information about beneficiaries can be provided through classifications.
 */
export type BeneficiaryLocation = Location1[];
/**
 * Details of the funder
 *
 * @minItems 1
 */
export type FundingOrg = [Organization, ...Organization[]];
/**
 * An identifier for this grant programme.
 */
export type Code = string;
/**
 * The title of this grant programme.
 */
export type Title2 = string | null;
/**
 * A description of this grant programme.
 */
export type Description4 = string | null;
/**
 * A web link to more details of this grant programme.
 */
export type URL1 = string | null;
/**
 * When was the link between this grant and its grant programme last modified? A full date-time should be given. Usually this can be generated automatically by the software managing or exporting this data.
 */
export type LastModified3 = string;
/**
 * Information about the grant programme under which the grant was awarded
 */
export type GrantProgramme = GrantProgramme1[];
/**
 * Was this grant made as the result of an open call for applications? Values must be 'Yes' or 'No'
 */
export type FromAnOpenCall = "Yes" | "No";
/**
 * A vocabulary used for this classification.
 */
export type Vocabulary = string;
/**
 * A codelist value in the chosen vocabulary.
 */
export type Code1 = string;
/**
 * The title of this classification.
 */
export type Title3 = string | null;
/**
 * A description of this classification.
 */
export type Description5 = string | null;
/**
 * A web link to more details of this classification.
 */
export type URL2 = string | null;
/**
 * When was this grant classification information last modified? A full date-time should be given. Usually this can be generated automatically by the software managing or exporting this data.
 */
export type LastModified4 = string;
/**
 * Information about the type of funding provided by the grant
 */
export type FundingType = Classification[];
/**
 * Information about a classification associated with the grant
 */
export type Classifications = Classification[];
/**
 * An identifier for this document.
 */
export type Identifier4 = string;
/**
 * The document title
 */
export type Title4 = string | null;
/**
 * The URL of the document.
 */
export type WebAddress1 = string | null;
/**
 * A description of the document
 */
export type Description6 = string | null;
/**
 * A document category. For example, 'Application Form', 'Photo' or 'Project Report'. In future, 360Giving will provide a codelist of document types.
 */
export type DocumentType = string | null;
/**
 * What was this information last modified? A full date-time should be given. Usually this can be generated automatically by the software managing or exporting this data.
 */
export type LastModified5 = string;
/**
 * Information about a document related to the grant
 */
export type RelatedDocument = Documents[];
/**
 * Identifier
 */
export type Identifier5 = string;
/**
 * When did this transaction take place? The date should be written as YYYY-MM-DD, or in full date-time format.
 */
export type TransactionDate = {
  [k: string]: unknown;
} & string;
/**
 * The total value of this transaction.
 */
export type Value = number;
/**
 * The date that this value was set (to allow historical currency conversion). The date should be written as YYYY-MM-DD, or in full date-time format.
 */
export type ValueDate = {
  [k: string]: unknown;
} & (
  | ({
      [k: string]: unknown;
    } & string)
  | (null & {
      [k: string]: unknown;
    })
);
/**
 * A description of this transaction.
 */
export type Description7 = string | null;
/**
 * The organisation identifier of the provider of transaction funds.
 */
export type Provider = string | null;
/**
 * The organisation identifier of the recipient of transaction funds.
 */
export type Recipient = string | null;
/**
 * When was information about this transaction last updated? A full date-time should be given. Usually this can be generated automatically by the software managing or exporting this data.
 */
export type LastModified6 = string;
/**
 * The identifiers of any related activities (e.g. other grants given as part of a multi-grant project)
 */
export type RelatedActivity = string[];
/**
 * When was information on this grant last updated? A full date-time format must be given. Usually this can be generated automatically by the software managing or exporting this data.
 */
export type LastModified7 = string;
/**
 * A web link pointing to the source of this data. This may be an original 360Giving data file, a file from which the data was converted, or an organisation website.
 */
export type DataSource = string | null;
/**
 * A code referring to the type of regranting process that this grant represents. The value for this field should be drawn from the Regrant Type codelist
 */
export type ForRegrantType = string;
/**
 * A code referring to the location scope applicable to this grant. The value for this field should be drawn from the Location Scope codelist.
 */
export type LocationScope = string;

/**
 * An event in the life of the grant activity
 */
export interface Event {
  title?: Title1;
  startDate?: StartDate;
  endDate?: EndDate;
  duration?: DurationMonths;
  description?: Description1;
  dateModified?: LastModified;
  [k: string]: unknown;
}
/**
 * Details of the recipient of this grant to an individual.
 */
export interface RecipientInd {
  id: Identifier1;
  name: Name;
  [k: string]: unknown;
}
export interface ToIndividualsDetails {
  primaryGrantReason?: PrimaryGrantReason;
  secondaryGrantReason?: SecondaryGrantReason;
  grantPurpose?: GrantPurpose;
  [k: string]: unknown;
}
export interface Organization {
  id: Identifier2;
  name: Name1;
  department?: Department;
  contactName?: ContactName;
  charityNumber?: CharityNumber;
  companyNumber?: CompanyNumber;
  streetAddress?: StreetAddress;
  addressLocality?: City;
  addressRegion?: County;
  addressCountry?: Country;
  postalCode?: PostalCode;
  telephone?: PhoneNumber;
  alternateName?: AlternateName;
  email?: Email;
  description?: Description2;
  organisationType?: OrganisationType;
  url?: WebAddress;
  location?: Location;
  dateModified?: LastModified2;
  [k: string]: unknown;
}
export interface Location1 {
  id?: Identifier3;
  name?: Name2;
  countryCode?: CountryCode;
  latitude?: Latitude;
  longitude?: Longitude;
  description?: Description3;
  geoCode?: GeographicCode;
  geoCodeType?: GeographicCodeType;
  dateModified?: LastModified1;
  [k: string]: unknown;
}
export interface GrantProgramme1 {
  code?: Code;
  title?: Title2;
  description?: Description4;
  url?: URL1;
  dateModified?: LastModified3;
  [k: string]: unknown;
}
export interface Classification {
  vocabulary?: Vocabulary;
  code?: Code1;
  title?: Title3;
  description?: Description5;
  url?: URL2;
  dateModified?: LastModified4;
  [k: string]: unknown;
}
export interface Documents {
  id?: Identifier4;
  title?: Title4;
  url?: WebAddress1;
  description?: Description6;
  documentType?: DocumentType;
  dateModified?: LastModified5;
  [k: string]: unknown;
}
export interface Transaction {
  id?: Identifier5;
  transactionDate?: TransactionDate;
  currency?: Currency;
  value?: Value;
  valueDate?: ValueDate;
  description?: Description7;
  provider?: Provider;
  recipient?: Recipient;
  dateModified?: LastModified6;
  [k: string]: unknown;
}
